name: Test
on:
  push:
    branches:
      - dev
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: actions/checkout@v2
        uses: actions/checkout@v2
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          distribution: corretto
          java-version: 1.8
      - name: Install Maven
        run: |
          #sudo yum install -y maven
          sudo apt-get update && sudo apt-get install -y maven
      - name: Build Maven
        run: mvn -B package --file pom.xml
      - name: Publish Artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ${{ github.workspace }}
          name: drop
